### PR TITLE
Polish views

### PR DESCRIPTION
**Pull request by mikailkarimi**
Resolves https://github.com/aryan-soni/eecs3311-project-bravo/issues/30

Polishing up the views. I updated the forecast model to now return a chart with the forecasted entries as well as some model information in the chart itself (deemed as required in the use case). Also of note, I updated the configure panel in the visualization frame with parameters that I arbitrarily thought could be configurable in the visualization model. The model for visualizations needs a bit of config for this as well as the controller for the visualizations. Otherwise, our codebase should now have matching inputs in the views for what the models require. 

New forecast output (the dip is the new values from the forecaster):
image

New configure frame: 
image

### CODE REVIEW

**Comment by aryan-soni** [comment]
Hi Mikail, thanks for looking into this!

I took a look at this with @o-saund and @manmeet-walia, and there are a few quick changes we’d suggest:

1. I think the Chart functionality should be decoupled from the model. The main purpose of the model should be to return data, I don’t think it’s optimal from a MVC standpoint to return a chart directly from the model. Ideally, the view can take in the relevant information and return the chart itself. It may have made sense in the Visualization model to do this, because in that the case the Visualization itself is the end product, but in this case it seems as a double array should be returned.
2. I can see some boilerplate code still remaining (e.g., Mortality/1000 births in the Visualization View). Could you tailor this to our application as well, or is there any information you’re missing?
3. Nit: I notice that the buttons say “Visualization View,” “Forecast View” etc., maybe we can just cut out the View part?
4. For the Form, I think we should restrict inputs for the start/end time and monthly/yearly fields to facilitate error handling, via something like a dropdown.
5. For the Summary Table, we basically only need two rows maximum (one for each time series). Could you add a row label that specifies that it’s Time Series 1 or Time Series 2 as well?
6. For the Visualization, I don’t think the Configure should show unless we select a specific option (i.e., it shouldn’t show initially because there’s nothing to configure). 
7. For the specific labels for the Visualization, run the BarVisualization and PlotVisualization models. You will see what the graphs should look like for each of them, so hopefully that would be helpful in terms of updating labels.
8. For the Forecast “Number of Months” input box, is there any way to limit it to a positive integer to facilitate error handling?
9. In the forecast graph, the years have commas. Is there any way to make the years format regularly?

By the way, regarding the Visualization Configuration, @o-saund will look into it. I’ve created an issue, it should be completed by Friday night or Saturday at the latest, and then you can make minor updates to the view based on that.

**Comment by mikailkarimi** [comment]
1. Done! Sounds good, yeah I thought it was weird as well to do it this way. I moved it to the view, uncomment the forecastGraph method when the data integration comes into play.
2. I left this because the visualization model will replace this temp graph. Let me know if I am missing something.
3. Done! 
4. Done!
5. Done! Configured the sizing to be capped at two basically. I will look into row headers if I style the application, there doesn't seem to be a nontrivial way to add them. 
6. Done!
7. Isn't this already configured in the respective models? I can change the name of Bar Visualization and Plot Visualization but I don't see an alternative.
8. Done!
9. I believe what you're catching is the hyphens. Let me know if I am missing something here as well.

**Review by aryan-soni — COMMENTED** [review]
Thanks for making the changes!

A few additional comments after testing it out with @o-saund:
1. When the form is initially loaded (with only 1 time series), the formatting for locations seems a tad off:
Screenshot 2023-03-24 at 9 49 04 PM
2. For the form, just to confirm, does the date range reflect the date range of our actual data?
3. Can you confirm if the rows for the summary table are capped at 2? They don't seem to be on my end.
image
4. Re: your question from Point 7, yeah — the model does take care of it, good point. Also, I know you're not sure what the visualizations look like, so below are the screenshots. I'd recommend setting up the DB when you get the chance based on the instructions in #20 

image
image

5. In terms of updating the configure window for the visualizations, the configurations for the visualization models were merged in #48. Check the `BarVisualization` and `PlotVisualization` files respectively, and read the comments there — they describe what needs to be configured and the parameters. Also, it may be worth looking into limiting the input via dropdowns or radio buttons or something similar.

6. The Forecasted Time Series seems a bit off. The following images show how they look when they initially render, and when they are expanded.
image
image

**Comment by mikailkarimi** [comment]
1. Nice catch! Should be good now.
2. Yup! It's based on the CSV.
3. Ah, I made the Raw Data table capped, should be good now, sorry about that.
4. Thank you. 
5. Really well put comments @o-saund, thank you! Made my job super easy.
6. This is because I have a commented-out graph in the view. When the controllers are linked they should be uncommented and the graph will render.

**Review by aryan-soni — COMMENTED** [review]
Thanks for the quick turnaround! Just a few more minor points, then it should be good to go 😅 

Let me know if you aren't able to replicate some of these bugs or errors, not sure if they're specific to me

1. The location dropdown seems a bit cut off on my end, any way we can fix this?
image

2. Is the raw table still capped at 2? We would no longer need the cap if so.

3. What does "Added Elements" Represent in the Configuration for the Bar Visualization? 

4. For the Configuration for the Bar Visualization, I think the margin of each bar should be able to be modified separately. Similar logic should hold for the Plot Visualization.

5.  If I switch to Plotted Visualization at the top, the Configure menu doesn't change — it still shows the Bar one.

6. When I am within a configuration, the Confirm Configuration button doesn't close the window.

**Comment by mikailkarimi** [comment]
Latest commit should be good, misunderstood the configuration tab initially.

**Review by aryan-soni — APPROVED** [review]
Thanks so much for all the changes.

I would recommend making these changes to the labels for the configurations, then feel free to merge.

For the Bar Visualization, make the labels:
* Bar Thickness for Time Series 1
* Bar Thickness for Time Series 2

For the Plot Visualization, make the labels:
* Line Thickness for Time Series 1
* Shape Thickness for Time Series 1
* Line Thickness for Time Series 2
* Line Thickness for Time Series 2

Hope that clears things up!

**Comment by aryan-soni** [comment]
Another change I think we need that just occurred to me.

Take a look at the other controllers, we basically don't instantiate any View -adjacent objects directly — this ensures that we adhere to SRP for the controllers.

Could you port over the Visualization logic to the views, and keep the Visualization controller similar to the other ones?

**Comment by manmeet-walia** [comment]
Decoupled the view and controller logic from each other, fixing the labels is next

**Comment by manmeet-walia** [comment]
Fixed the labels for the configuration menu

**Comment by manmeet-walia** [comment]
Made changes to the plot visualization config menu (changed them to radio buttons that represent enable and disable)

**Comment by mikailkarimi** [comment]
Thanks for finishing this off Manmeet, should be good to merge now right?

**Review by aryan-soni — APPROVED** [review]
Took a second look. Thanks for taking the rest of it on @manmeet-walia

**Pull request merged**
