### PR TITLE
Add Forecast model

### LINKED ISSUE #29: Models for Forecasting
Need to create models for forecasting.

After some exploration, it seems like this is a matter of pinpointing which methods from the API would be semantically useful and then implementing them within the models. Refer to the pre-existing models and the notes doc for insight on the general advised structure.

### PR DESCRIPTION
**Pull request by mikailkarimi**
Resolves #29 

This took so long because there wasn't a single tutorial online for this. I added the forecasting model and tested using the data that the professor provided. This worked really well, if you want me to pair and show this off let me know and I can show it off! 
We need to configure the modal based on the controller but the major logic is here and commented on. 

I used two local jar files for this, the timeseriesForecasting-1.1.27.jar as well as the weka.jar from the full weka installation. Weka is also decently outdated and only works with SDK version 11. This could be of concern but shouldn't be too hard to figure out.

### CODE REVIEW

**Review by o-saund — COMMENTED** [review]
Hey Mikail, got some good work done here, let's go! Here's some changes I think you may want to take a look at and change.

1. Because we are implementing our project with MVC architecture we need this model to communicate with the controller to update the views. If you have any ideas on how to do this please do share and implement them in the model. I suggest that you take a look at our other models which are completed as they have this functionality built in.
2. Currently, there is no test for this class we should either implement a test function or a simple PSVM test that would be greatly useful for the above (controller integration) and show the functionality of the forecasting.
3.  Currently in the model I don't see how exactly a user is supposed to input data so that we can use it for forecasting, we need this functionality to be implemented in the model and you can take a look at the previously implemented models for the general gist on how to do it. You may have to do some conversions or create a new CSV file or something through code, just some ideas.
4. It may be prudent to look at how we communicate with the SQL Database as currently, the code is directly taken from the CSV file which may also help with the user input.
5. Final thing, just take a look at the other models and how QueryResult is used it may help you with a lot of the problems specified above.

**Comment by o-saund** [comment]
> Hey Mikail, got some good work done here, let's go! Here's some changes I think you may want to take a look at and change.
> 
> 1. Because we are implementing our project with MVC architecture we need this model to communicate with the controller to update the views. If you have any ideas on how to do this please do share and implement them in the model. I suggest that you take a look at our other models which are completed as they have this functionality built in.
> 2. Currently, there is no test for this class we should either implement a test function or a simple PSVM test that would be greatly useful for the above (controller integration) and show the functionality of the forecasting.
> 3. Currently in the model I don't see how exactly a user is supposed to input data so that we can use it for forecasting, we need this functionality to be implemented in the model and you can take a look at the previously implemented models for the general gist on how to do it. You may have to do some conversions or create a new CSV file or something through code, just some ideas.
> 4. It may be prudent to look at how we communicate with the SQL Database as currently, the code is directly taken from the CSV file which may also help with the user input.
> 5. Final thing, just take a look at the other models and how QueryResult is used it may help you with a lot of the problems specified above.

really good work otherwise well done!

**Comment by aryan-soni** [comment]
Thanks for looking into this!

I wasn't able to test it locally. I tried creating a `main` method and instantiating a `Forecast` object, and got this error:

```
 Exception in thread "main" java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix
        at weka.classifiers.timeseries.WekaForecaster.<init>(WekaForecaster.java:82)
        at models.Forecast.<init>(Forecast.java:21)
        at models.Forecast.main(Forecast.java:56)
```

I did configure dependencies locally, so not sure why the error is occurring.

Either way, I'm aligned with Onkar's feedback:
1. We want to minimize the work the controller does, and put most of the weight on the model. I'd recommend taking a look at the `nhpiComparison` model as a reference point. Basically, assume that you'll receive a `QueryResult` object as input, and then run the forecasting on it.
2. As Onkar mentioned, in general, we don't want to be communicating with the CSV file directly as that violates DIP.
3. Also, as Onkar mentioned, a `main` method with specific tests would be helpful.

Thanks again, and looking forward to seeing the Forecasting in play.

**Comment by aryan-soni** [comment]
Additional note that just occurred to me: shouldn't this class be able to taken in model parameters as well and adjust the forecasting as such? The use cases file for file specifies that some degree of customization should be implemented.

**Comment by mikailkarimi** [comment]
PR should be good now! I added:
- a solution to the error Aryan was running into with `WekaPackageManager.loadPackages(false);`
- additional model parameters by giving users the choice of which model they would like to use (SMO or LR)
- PSVM testing (I used mock data as I do not have access to the DB, it is very much like the dataset given)
- controller configuration. Meaning the model now takes in a query result and builds its own CSV file based on the input. It outputs an ArrayList of doubles with the forecasted values

Let me know if there are any concerns! Thanks for all the detailed feedback.

**Comment by aryan-soni** [comment]
> PR should be good now! I added:
> 
> * a solution to the error Aryan was running into with `WekaPackageManager.loadPackages(false);`
> * additional model parameters by giving users the choice of which model they would like to use (SMO or LR)
> * PSVM testing (I used mock data as I do not have access to the DB, it is very much like the dataset given)
> * controller configuration. Meaning the model now takes in a query result and builds its own CSV file based on the input. It outputs an ArrayList of doubles with the forecasted values
> 
> Let me know if there are any concerns! Thanks for all the detailed feedback.

Attempted to test things out, now getting this error:

```
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @1796cf6c
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
        at weka.core.WekaPackageClassLoaderManager.injectClasses(WekaPackageClassLoaderManager.java:792)
        at weka.core.WekaPackageClassLoaderManager.injectAllClassesInFromStream(WekaPackageClassLoaderManager.java:690)
        at weka.core.WekaPackageClassLoaderManager.injectMTJCoreClasses(WekaPackageClassLoaderManager.java:118)
        at weka.core.WekaPackageManager.<clinit>(WekaPackageManager.java:255)
        at models.Forecast.main(Forecast.java:87)
Exception in thread "main" java.lang.NoClassDefFoundError: no/uib/cipr/matrix/Matrix
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at weka.core.WekaPackageClassLoaderManager.forName(WekaPackageClassLoaderManager.java:198)
        at weka.core.WekaPackageClassLoaderManager.forName(WekaPackageClassLoaderManager.java:178)
        at weka.core.ClassDiscovery.find(ClassDiscovery.java:247)
        at weka.gui.GenericPropertiesCreator.generateOutputProperties(GenericPropertiesCreator.java:542)
        at weka.gui.GenericPropertiesCreator.execute(GenericPropertiesCreator.java:639)
        at weka.gui.GenericPropertiesCreator.<clinit>(GenericPropertiesCreator.java:167)
        at weka.core.WekaPackageManager.refreshGOEProperties(WekaPackageManager.java:1504)
        at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1429)
        at weka.core.WekaPackageManager.loadPackages(WekaPackageManager.java:1305)
        at models.Forecast.main(Forecast.java:87)
Caused by: java.lang.ClassNotFoundException: no.uib.cipr.matrix.Matrix
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 12 more
```

Also, quick question, saw this note:  _Size limit on the dataset, possibly filter this with IO_. Could you elaborate on what you're referring to?

**Comment by mikailkarimi** [comment]
For anyone else trying to test this locally, make sure to set your JDK to version 11. Open to pairing if you need to get unblocked. This was the most annoying part about this issue zzzzzzzzz.

**Comment by manmeet-walia** [comment]
Hi @mikailkarimi,

I had the opportunity to take a look at your PR and have a concern regarding the JDK dependency issue. To begin with, I believe that locking off our code to a specific dependency is not the way we want to approach this. This might cause a bunch of issues when it comes to running our program and testing, as well as the fact that it might interfere with other functionalities. Could you possibly take a look into what is the root cause of the error and make fixes such that it runs under any JDK. Such a change will pay massive dividends for the usability of our application and would avoid any sort of potential developmental headaches that may arise as a result.

Thanks, Manmeet

**Comment by mikailkarimi** [comment]
Hey Manmeet, I understand the concern. Weka is a really outdated dependency and will not function under newer SDK's hence the issue. I tested it out using Java 1.8 and the framework worked. This is a much newer version of Java relative to Java 11 so we should not have any complications using Java 1.8. Thanks for the comment, let me know if you have any other concerns.

**Review by aryan-soni — APPROVED** [review]
LGTM. Just to confirm, the files that are created can be overwritten if the forecast configurations receive new inputs, correct?

**Comment by mikailkarimi** [comment]
Yup! They will be overwritten. The size of the input is also not a concern as long as we filter by location and time which will happen ^_^

**Review by o-saund — APPROVED** [review]
lgtm ^_^ Thanks for taking the time to read my comment and implementing the necessary changes. Looking forward to the views 🔥 !!

**Pull request merged**
